### ISSUE TITLE
Version 2.0

### ISSUE THREAD

**Issue by Darkflame72** [Obsidion-dev/Obsidion#303]
This will add full slash command integration and a new interface. It will also remove the normal interface of directly reading messages.

TODO:

**Enhancements:**

- [ ]  Embeds as responses #294 
- [ ] Hypixel Stats #224 
- [ ] Minecraft server info #156 
- [ ] Compare Players #50 
- [ ] Minecraft Bug Info #86 
- [ ] Minecraft recipe #157 
- [ ] Remove normal commands

**Fixes:**

- [ ] #289 
- [ ] #236

**Comment by Darkflame72** [comment]
News will be fixed by #311
