### ISSUE TITLE
Roadmap Version 1

### ISSUE THREAD

**Issue by Darkflame72** [Obsidion-dev/Obsidion#85]
Version 1 release roadmap in no particular order

- [ ] Dashboard
- [ ] Rcon
- [ ] New profile picture
- [x] Link Minecraft server to discord guild
- [x] Hypixel commands
- [ ] Minecraft server posting (reliable)
- [ ] Compare Minecraft player stats from servers
- [ ] auto roles from server ranks
- [ ] stats recording
- [ ] UHC commands
- [x] Add cache

Any more ideas comment below
